### ISSUE TITLE
AssetLib edit references untagged version

### ISSUE THREAD

**Issue by akien-mga** [Mainman002/MFPanel#1]
Hi there,

In your Asset Library submission ( https://godotengine.org/asset-library/asset/edit/599 ) you reference `v1.0` as the version to download, but there is no `v1.0` tag, so the Asset Library doesn't know what should be downloaded.

You should either tag `v1.0` on the corresponding commit, or edit your asset lib submission to point to a commit hash.

**Comment by Mainman002** [comment]
ahh thank you! (I'm sorry still figuring out how to use github xD) I didn't even think about the releases tab until you mentioned tags. . . ok I think I fixed it, so let me know if there's anything else I need to do

**Comment by akien-mga** [comment]
That works fine, thanks! :)

**Comment by Mainman002** [comment]
Awesome! no prob, and thank you!

**Comment by Mainman002** [comment]
so quick question, how do I fix the missing icons? (sorry once I get that figured out I should be finished bugging you xD)

**Comment by akien-mga** [comment]
I think the assetlib expects a link to the raw PNG ( https://raw.githubusercontent.com/Mainman002/MFPanel/MFPanel(Godot3)/icon.png ) instead of its GitHub page ( https://github.com/Mainman002/MFPanel/blob/MFPanel(Godot3)/icon.png ). You get the raw URL by pressing the "Download" button on the GitHub page.

**Comment by Mainman002** [comment]
ahh cool, ok that works great, what about youtube videos? should I just link an image in the top text input, and then the youtube link in the bottom, or should I upload the video to github? (I mean the second is a bit extreme but I figured I'd ask anyway Lol)

**Comment by akien-mga** [comment]
I'm not sure, the UI is a bit confusing I think :D Calling @bojidar-bg to the rescue!

**Comment by Mainman002** [comment]
ok I think the top text input is where you post the image / youtube url link, and the bottom is where you can set a thumbnail image. . . I was pretty sure someone figured out how to play videos in godot but I might be thinking of other things. . . anyway I cleaned up my github files to work with Godot, so sorry about that. . . I'll try not to update it too often Lol
